### ISSUE TITLE
[Missing data]: Bittler and Carpenter

### ISSUE THREAD

**Issue by ruchikamajumdar96** [AEADataEditor/aeadataeditor.github.io#16]
### Contact Details

majumda1@uci.edu

### DOI of the article

10.1257/pol.20120298

### DOI of the replication package

https://doi.org/10.3886/E114559V1

### Reproducibility

- [X] I can provide evidence of full reproducibility of the problem.

### Platform used for providing evidence

- [ ] WholeTale
- [ ] CodeOcean
- [ ] Social Science Reproduction Platform
- [ ] Github
- [ ] ReplicationWiki
- [ ] Gitlab
- [ ] Dataverse
- [X] openICPSR

### Relevant evidence of problem - full document

https://www.openicpsr.org/openicpsr/project/114559/version/V1/view?path=/openicpsr/114559/fcr:versions/V1/AEJPOL-2012-0298-replication/final-bitler-carpenter-brfss-data-not-event-study.csv.txt&type=file

### Relevant evidence of problem - narrative

Corrupted data file. Cannot open on my computer, need to fix file. 

FIle name: final-bitler-carpenter-brfss-data-not-event-study.csv.txt

**Comment by larsvilhuber** [comment]
Noted. I am following up. Note that this is corrupted at the source (back in 2016), the file cannot be fixed. I will query the authors.

**Comment by larsvilhuber** [comment]
Data have been received, but I need to re-publish it.

**Comment by larsvilhuber** [comment]
This has been completed. https://doi.org/10.3886/E114559V2
