### ISSUE TITLE
[Missing data]: Sequeira (2016)

### ISSUE THREAD

**Issue by jonathandroth** [AEADataEditor/aeadataeditor.github.io#17]
### Contact Details

jonathanroth@brown.edu

### DOI of the article

https:/doi.org/10.1257/aer.20150313

### DOI of the replication package

https://doi.org/10.3886/E113044V1

### Reproducibility

- [X] I can provide evidence of full reproducibility of the problem.

### Platform used for providing evidence

- [ ] WholeTale
- [ ] CodeOcean
- [ ] Social Science Reproduction Platform
- [ ] Github
- [ ] ReplicationWiki
- [ ] Gitlab
- [ ] Dataverse
- [ ] openICPSR

### Relevant evidence of problem - narrative

The replication code provided does not run out of the box. Line 8 of Replication_Code.do (the first line after a clear) is

`use Trade_Flow.dta`

However, Trade_Flow.dta is not included. There is a file titled Trade_Flow**s**.dta, which was likely intended. 
If that file is loaded, however, then line 12 attempts to create a variable `share_value`, which is already contained in the dataset, thus yielding the error, "variable share_value already defined"

The code should be updated to reference the correct datasets, and such that the provided commands run without error.

**Comment by larsvilhuber** [comment]
Updated code and data have been received, waiting for submission to re-publish.

**Comment by larsvilhuber** [comment]
This is completed: https://doi.org/10.3886/E113044V2
