### ISSUE TITLE
[Missing data]: 

### ISSUE THREAD

**Issue by michaeldarisse** [AEADataEditor/aeadataeditor.github.io#18]
### Contact Details

mdarisse@fsu.edu

### DOI of the article

https://doi.org/10.1257/pandp.20231124

### DOI of the replication package

http://doi.org/10.3886/E190063V1

### Reproducibility

- [X] I can provide evidence of full reproducibility of the problem.

### Platform used for providing evidence

- [ ] WholeTale
- [ ] CodeOcean
- [ ] Social Science Reproduction Platform
- [ ] Github
- [ ] ReplicationWiki
- [ ] Gitlab
- [ ] Dataverse
- [ ] openICPSR

### Relevant evidence of problem - narrative

All files in the replication package are showing up empty. I tried downloading the package on a couple different computers and got the same result.

**Comment by larsvilhuber** [comment]
Tracked by internal ID AEAREP-4767.

**Comment by larsvilhuber** [comment]
This has been updated: new version has been published: https://doi.org/10.3886/E190063V2
