### ISSUE TITLE
[Missing data]: 

### ISSUE THREAD

**Issue by mehdibarati1** [AEADataEditor/aeadataeditor.github.io#19]
### Contact Details

Mehdi.Barati@usm.edu

### DOI of the article

https://doi.org/10.1257/aer.20211218

### DOI of the replication package

https://doi.org/10.3886/E175582V1

### Reproducibility

- [X] I can provide evidence of full reproducibility of the problem.

### Platform used for providing evidence

- [ ] WholeTale
- [ ] CodeOcean
- [ ] Social Science Reproduction Platform
- [ ] Github
- [ ] ReplicationWiki
- [ ] Gitlab
- [ ] Dataverse
- [X] openICPSR
- [X] Personal Computer

### Relevant evidence of problem - full document

The missing data should be available at this location:
(https://www.openicpsr.org/openicpsr/project/175582/version/V1/view?path=/openicpsr/175582/fcr:versions/V1/Data/Input&type=folder).

### Relevant evidence of problem - narrative

I am Mehdi Barati, an economics professor at the University of Southern Mississippi. Currently, I am attempting to replicate the findings of the paper "Social Media and Mental Health" by Braghieri, Luca, Ro'ee Levy, and Alexey Makarin, published in the American Economic Review (Vol. 112, No. 11, pp. 3660-93, 2022). To do so, I am utilizing the provided replication package, available at:  (https://www.aeaweb.org/articles?id=10.1257%2Faer.20211218&ref=twelvetables.blog). 

However, I have encountered an obstacle. The replication package requires the presence of the file "ACHA_dataset_virgin.dta" in the directory Data > Input, as indicated in the code file "Data_Prep_ACHA_1.do" accessible here: (https://www.openicpsr.org/openicpsr/project/175582/version/V1/view?path=/openicpsr/175582/fcr:versions/V1/Code/Data_Preparation/Data_Prep_ACHA/Data_Prep_ACHA_1.do&type=file). 

Unfortunately, this essential dataset seems to be missing. Please let me know if you need anything else on my end. 

Best,
Mehdi Barati, PhD

**Comment by larsvilhuber** [comment]
@mehdibarati1 This is expected behavior. As the README states,

```
The data are not publicly available
and are not provided in the
replication package. In order to
obtain them, one can contact
Valerie Hartman, Senior Research
Coordinator at the ACHA
(vhartman@acha.org), and
complete the application form.
Additional information can be found
on the website
```
(Page 3 of the README).
