### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by karldw** [AEADataEditor/aeadataeditor.github.io#4]
Hi,

Thanks for all your work! Browsing around the https://aeadataeditor.github.io website, I noticed a few of the links on the website were broken, and thought you would want to know. Here are the broken links I found.

1. The "Protocol" link on p102 of [these slides](https://zenodo.org/record/4311917) points to https://aeadataeditor.github.io/aea-de-guidance/protocol-3rd-party-replication.html, but that page doesn't exist.
2. The template README on p112 of those same slides points to https://aeadataeditor.github.io/aea-de-guidance/template-README.html, but that page doesn't exist.
3. The FAQ link at the top of every page points to https://aeadataeditor.github.io/aea-de-guidance/faq.html, but that page doesn't exist.
4. The "EDIT" on Github link at the bottom of every page points to https://github.com/AEADataEditor/aeadataeditor.github.io/blob/main/, which is a 404 for me.

Thanks,
Karl

**Comment by larsvilhuber** [comment]
My apologies for not seeing this. I think I caught a few of these over the months myself, but I'll double-check these to see if they work now.

**Comment by larsvilhuber** [comment]
Closing this out. 1 and 2 are not fixable - those are from an old presentation, and the website has changed somewhat since. For [1] see https://www.aeaweb.org/journals/data/policy-third-party, for [2] see https://social-science-data-editors.github.io/template_README/. The other two work for me now.
